### ISSUE TITLE
quat_mul_vec3 causes SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by macarion** [datenwolf/linmath.h#20]
It seems that the `quat_mul_vec3` function takes in a `vec3` as a result parameter and then passes it on to several other functions expecting a `quat`, resulting in an *Address boundary error*.

**Comment by datenwolf** [comment]
Oops. Mea culpa. Will fix ASAP.

**Comment by datenwolf** [comment]
Just fixed the issue by replacing the whole code with a more elegant method for quaternion vector multiplication.
