### ISSUE TITLE
mat4x4_rotate_z, order of operation intended?

### ISSUE THREAD

**Issue by BenjaminRenz** [datenwolf/linmath.h#30]
I tried this function with a translation Matrix as input for M. When I use the resulting matrix it first rotates around the origin and after that, it translates, but given the functions description, I would have thought that it would take the transformation and add the operation "rotate around the origin" afterwards.
Is that behaviour intended?

```
static inline void mat4x4_rotate_Z(mat4x4 Q, mat4x4 M, float angle)
{
	float s = sinf(angle);
	float c = cosf(angle);
	mat4x4 R = {
		{   c,   s, 0.f, 0.f},
		{  -s,   c, 0.f, 0.f},
		{ 0.f, 0.f, 1.f, 0.f},
		{ 0.f, 0.f, 0.f, 1.f}
	};
	mat4x4_mul(Q, M, R);
}
```

To get this behaviour I expected I had to change :
`	mat4x4_mul(Q, M, R);` to `	mat4x4_mul(Q, R, M);`

Edit: 21.04.21 fix code formatting

**Comment by datenwolf** [comment]
It depends on if you assume row or column vectors being multiplied with the resulting rotation matrix. Exchanging the direction in which is multiplied also implies transposition of everything (matrices, vectors) involved.

Can you show your code you tested with?

**Comment by BenjaminRenz** [comment]
Sorry, that took a bit of time.  I'm using a mat3x3 adaptation of your code, only the names mat4x4 and the for loop borders changed. The code gets four points as pixel positions from a camera and tries to create a matrix that creates a matrix which will later be used to map new pixel positions on a grid.
The four calibration points are the borders of the stretched and deformed grid in camera coordinates and when calling camera_perspec_map_point with another point this returns the position in on the deformed grid.
While creating the matrix which will be used to transform the point in camera coordinates on the grid need to bring the points to the form
          ____─── C
┌───          /
│                /
│              /
└─────┘

Where points A,B,D are on (0,0,1), (1,0,1), (0,1,1) and point C is still on an arbitrary position. For that i need to rotate the tetragon around point A to match side AB with the x-Axis, after having the point a translated to the origin, but when using the original function it does not bring side AB on the x-Axis because the rotation is applied before translating point A to the origin.
Therefore I altered the function mat4x4_rotate_z to mat3x3_rotate_delayed_Z by swapping the arguments of mat3x3_mul.
I have copied the header and source into one file called example.c .

If you need additional information please ask.
Greeting Benjamin

[examplecode.txt](https://github.com/datenwolf/linmath.h/files/2852635/examplecode.txt)

**Comment by BenjaminRenz** [comment]
> 
> 
> It depends on if you assume row or column vectors being multiplied with the resulting rotation matrix. Exchanging the direction in which is multiplied also implies transposition of everything (matrices, vectors) involved.
> 
> Can you show your code you tested with?

I was thinking about this in the following way:
First translate then rotate:
/ c  s 0\  .... /1 0 a \ . . /x\\
| -s c 0 | * | 0 1 b | * | y |
\ 0  0 1/  .....\ 0 0 1/ .. \1/
First rotate then translate:
/ 1 0 a\  .... /c -s 0 \ .. /x\\
| 0 1 b | * | s . . c  0 | * | y |
\ 0  0 1/  .....\ 0 0 1/ .. \1/

It should not make a difference to view that in row/column major format?
just transpose everything and completely invert the order...

Maybe I'm wrong but by trying first translating and then rotating arbitrary points I think I could observe that rotate_z does it if pass the translation matrix as an argument first rotate everything and after that applies the transformation.
Maybe you could make two functions and give them unambiguous names?

**Comment by BenjaminRenz** [comment]
> 
> 
> It depends on if you assume row or column vectors being multiplied with the resulting rotation matrix. Exchanging the direction in which is multiplied also implies transposition of everything (matrices, vectors) involved.
> 
> Can you show your code you tested with?

Recently came back to this and I just realized where the my problem lies.

I always thought that the note in the readme 
`computations are done in column major order` 
just refers to how the matrices are indexed as `m[n-th colum][m-th row]` and does not specify how which format the vectors are.

Then I looked on how translation matrices are constructed https://github.com/datenwolf/linmath.h/blob/05387571f57224f8cbc2b390b423dab6b9158988/linmath.h#L185-L191
According to http://steve.hollasch.net/cgindex/math/matrix/column-vec.html

> If you're using column vectors, your 4x4 translation components are in the right column. 

Therefore I assumed that the vectors must be column vectors from hereon.

But this contradicts the way rotation, etc. behave.

They follow the convention of OpenGl, meaning the matrices get POST multiplied (from the right) on an imaginary stack that is the previous or temporary matrix, while I would have expected the multiplication order to be like the "mathematical" way, there matrix operations are PRE multiplied and the vectors are colum major. 

I would have epected this behavior for row vectors, where the matrices are applied from the right onto the vector `vec4_res=vec4_in*mat4x4_rot*mat4x4_trans` and the multiplication of `mat4x4_rot*mat4x4_trans` will get combined into one matrix. The translation is multiplied onto the translation from the right.

So I think there are two parts to this, first how are the vectors represented (column or row vectors) and the second one is the multiplication order of matrices.

Could you please correct me if I'm wrong, but I suspect that linmath uses column vectors and post multiplication for matrices.

Thanks for taking a look, I'm still not sure if I approach this the right way, so I would be interested in your angle on this. 
Maybe you could add a note on the multiplication and vector representation in the readme.

**Comment by datenwolf** [comment]
> Could you please correct me if I'm wrong, but I suspect that linmath uses column vectors and post multiplication for matrices.

Yes, that's what it does. It does so, to follow the conventions set by the fixed function OpenGL pipeline. Assuming you have some OpenGL FFP code that uses the matrix stack, by replacing all of the OpenGL matrix stack functions with their corresponding linmath.h counterparts, and post multiplying vectors, the results should be identical (within the margins of floating point errors if fast-math is used). That's how it shall be; if not, then that's unintentional.

However I should point out that linmath.h found far wider adoption than I ever dreamt of; the whole thing began its life in a [rural restaurant in southern Germany](https://goo.gl/maps/kHvQf6rUYndv2aoD9), without me having an internet connection available and I also didn't bring along linear algebra text books to cross reference. What I brought along was a space mouse which USB protocol I intended to reverse engineer. That went quicker than anticipated and I needed some matrix math functions, so I had to write them down from memory or deduce things from first principles ad-hoc. I may or may not have flipped some indices then.

I feel like eventually I'll have to write a heir to linmath.h

**Comment by BenjaminRenz** [comment]
Thanks for the quick answer,
I like the simplicity of the current library.

The colum / row major vector or pre-/post multiplication thing is, at least how I see it, a bit like the inverted z-direction in Gl vs Vulkan. Both systems are intuitive to work in. But if you forget for a second that a different system is used it can produce some problems that are potentially difficult to find.

Also changing the vector format of the translation function is probably a bad idea as it would break existing code which relies on the behavior of colum vectors.

If I find some time I was thinking about adding some lines on the gl like usage / vector format to the readme. I will create a PR then.

Thanks for the libary, used it in multiple projects. 👍
