### ISSUE TITLE
Issue with constructing vectors

### ISSUE THREAD

**Issue by HugoPeters1024** [datenwolf/linmath.h#35]
Hiya, Loving this module so far, but I have an issue constructing a 3 dimension vector.
I have a large array of floats that represent 3d vertices. I wish to loop over them on a per vertex basis so i constructed the following piece of code.

```cpp
for(int i=0; i<n; i++) {
   vec3 v = VEC3(array[i+0], array[i+1], array[i+2]);
}
```

But this gives me the following compile error (using g++) 
```
linmath.h:148:30: error: array must be initialized with a brace-enclosed initializer
  #define VEC3(x,y,z)   (vec3){x,y,z}
                              ^~~~~~~
vertexbuf.h:76:17: note: in expansion of macro ‘VEC3’
       vec3 p1 = VEC3(grid[i+0], grid[i+1], grid[i+2]);
```

Am I doing something wrong here?

**Comment by datenwolf** [comment]
Well, to initialize a struct you can omit the `(vec3)` and just write 

    vec3 v = {array[i+0], array[i+1], array[i+2]};

No need for that `VEC3` macro.

**Comment by HugoPeters1024** [comment]
Thanks! Makes sense. Still wondering what the macro is for then.

**Comment by datenwolf** [comment]
The macro is for returning vec-s from functions.

```
vec3 foobar(…)
{
    /* ... */
    return VEC3(a,b,c);
}
```
