### ISSUE TITLE
warning: return type defaults to int

### ISSUE THREAD

**Issue by RicardasSim** [datenwolf/linmath.h#36]
warning: return type defaults to ‘int’ [-Wimplicit-int]
 LINMATH_H_FUNC mat4x4_arcball(mat4x4 R, mat4x4 M, vec2 _a, vec2 _b, float s)

in commit "transplanted arcball function"

static inline void mat4x4_arcball(mat4x4 R, mat4x4 M, vec2 _a, vec2 _b, float s)
was changed to:
LINMATH_H_FUNC mat4x4_arcball(mat4x4 R, mat4x4 M, vec2 _a, vec2 _b, float s)

missing void

LINMATH_H_FUNC void mat4x4_arcball(mat4x4 R, mat4x4 M, vec2 _a, vec2 _b, float s)

**Comment by datenwolf** [comment]
Fixed.
